### ISSUE TITLE
Container based on ActiveMQ image not starting in Windows 10

### ISSUE THREAD

**Issue by giuliopulina** [stratospheric-dev/stratospheric#258]
### What's going wrong and not working?

Hi,

I found an issue while testing with docker-compose.yml: the container based on stratospheric/activemq-docker-image has some issues during startup.
It is easy to reproduce the error also outside of docker-compose:

`docker run -p 5672:5672 -p 61613:61613 -p 61614:61614 -p 61615:61615 --rm --name test-active-mq-stratospheric stratospheric/activemq-docker-image`

returns this error:

`
WARN | Failed startup of context o.e.j.w.WebAppContext@34585ac9{ActiveMQ Console,/admin,file:///opt/activemq/webapps/admin/,UNAVAILABLE}
org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/WEB-INF/webconsole-embedded.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/webconsole-embedded.xml]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:342) ~[spring-beans-5.3.25.jar:5.3.25]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[spring-beans-5.3.25.jar:5.3.25]
`

### Expected outcome

The container based on ActiveMQ image should start without errors.

**Comment by rieckpil** [comment]
Thanks for reporting this, we'll investigate it further 👍
