### ISSUE TITLE
LocalStack currently doesn't seem to confirm SNS subscriptions

### ISSUE THREAD

**Issue by BjoernKW** [stratospheric-dev/stratospheric#39]
LocalStack in our current setup either doesn't seem to confirm SNS subscriptions or it doesn't send messages to subscribers. Providing an endpoint with host.docker.internal as host doesn't work either.

**Comment by BjoernKW** [comment]
https://hub.docker.com/r/s12v/sns could be another option. However, currently this error crops up when publishing a message to an SNS topic via HTTP on Fake SNS: https://github.com/s12v/sns/blob/master/example/config/elasticmq.conf

`fake-sns_1    | akka.camel.AkkaCamelException: Connection refused (Connection refused)
fake-sns_1    | 	at akka.camel.ProducerSupport$$anonfun$produce$1.applyOrElse(Producer.scala:77) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.actor.Actor.aroundReceive(Actor.scala:517) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.actor.Actor.aroundReceive$(Actor.scala:515) ~[sns.jar:0.4.1]
fake-sns_1    | 	at me.snov.sns.actor.ProducerActor.aroundReceive(ProducerActor.scala:14) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[sns.jar:0.4.1]
fake-sns_1    | Caused by: java.net.ConnectException: Connection refused (Connection refused)
fake-sns_1    | 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at java.net.Socket.<init>(Socket.java:286) ~[na:1.8.0_111-internal]
fake-sns_1    | 	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.camel.component.http.HttpProducer.executeMethod(HttpProducer.java:288) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:170) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[sns.jar:0.4.1]
fake-sns_1    | 	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.camel.ProducerSupport$ProducerChild.produce(Producer.scala:141) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.camel.ProducerSupport$ProducerChild$$anonfun$receive$1.applyOrElse(Producer.scala:115) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.actor.Actor.aroundReceive(Actor.scala:517) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.actor.Actor.aroundReceive$(Actor.scala:515) ~[sns.jar:0.4.1]
fake-sns_1    | 	at akka.camel.ProducerSupport$ProducerChild.aroundReceive(Producer.scala:112) ~[sns.jar:0.4.1]
fake-sns_1    | 	... 9 common frames omitted`

**Comment by BjoernKW** [comment]
Please also refer to this LocalStack issue: https://github.com/localstack/localstack/issues/3314

**Comment by BjoernKW** [comment]
Won't fix because we're now using Amazon MQ instead of SNS anyway.
